#
# FULLOCK - Fast User Level LOCK library
#
# Copyright 2015 Yahoo Japan Corporation.
#
# FULLOCK is fast locking library on user level by Yahoo! JAPAN.
# FULLOCK is following specifications.
#
# For the full copyright and license information, please view
# the license file that was distributed with this source code.
#
# AUTHOR:   Takeshi Nakatani
# CREATE:   Wed 7 Dec 2016
# REVISION:
#

language: cpp

sudo: required

dist: trusty

env:
  global:
    - PCUSER=antpickax
    - PCREPO=current
  matrix:
    - OS=centos TAG=centos7 DISTTAG=el/7 INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems"
    - OS=centos TAG=centos6 DISTTAG=el/6 INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems"
    - OS=fedora TAG=28 DISTTAG=fedora/28 INSTPKG="git autoconf automake gcc gcc-c++ gdb make libtool pkgconfig redhat-rpm-config rpm-build ruby-devel rubygems"
    - OS=ubuntu TAG=18.04 DISTTAG=ubuntu/bionic INSTPKG="git autoconf autotools-dev gcc g++ make gdb dh-make fakeroot dpkg-dev devscripts libtool pkg-config ruby-dev rubygems rubygems-integration"
    - OS=debian TAG=stretch DISTTAG=debian/stretch INSTPKG="git autoconf autotools-dev gcc g++ make gdb dh-make fakeroot dpkg-dev devscripts libtool pkg-config ruby-dev rubygems rubygems-integration"

cache: apt

services:
  - docker

before_install:
 - sudo apt-get update -qq
 - echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null
 - sudo service docker restart
 - sleep 5
 - sudo docker image pull ${OS}:${TAG}

script:
 - env
 - sudo docker container run --rm=true -e TRAVIS_TAG=${TRAVIS_TAG} -e FORCE_BUILD_PKG=${FORCE_BUILD_PKG} -e USE_PC_REPO=${USE_PC_REPO} -e BUILD_NUMBER=${BUILD_NUMBER} -e DEBFULLNAME=${DEBFULLNAME} -e DEBEMAIL=${DEBEMAIL} -e PCTOKEN=${PACKAGECLOUD_TOKEN} -v `pwd`:/fullock:rw ${OS}:${TAG} /bin/sh -c "/fullock/buildutils/travis_builder.sh -${OS} -pcuser ${PCUSER} -pcrepo ${PCREPO} -pcdist ${DISTTAG} ${INSTPKG}"

#
# VIM modelines
#
# vim:set ts=4 fenc=utf-8:
#
